### ISSUE TITLE
请问发信息是怎么实现的？

### ISSUE THREAD

**Issue by jazzii36** [Dragon-GCS/LOLHelper#3]
我有个想法，想做一个打野出现位置报警：“打野出现在上半区”，基于图像识别去做。
发消息是借助什么工具实现的？

**Comment by Dragon-GCS** [comment]
游戏启动的时候会启动一个本地服务器，通过socket连接之后可以向服务器发送请求，达到客户端发送消息的效果（客户端里边聊天框发消息就是向服务器发请求）。但是具体接口我不清楚，你可以在`helper\lcu.py`里边的`handle_ws_response`这个函数打印出来每次请求的url，自己分析一下。

**Comment by jazzii36** [comment]
来信已收到，谢谢。

**Comment by jazzii36** [comment]
来信已收到，谢谢。
